### ISSUE TITLE
Shortcuts assigned to wrong windows

### ISSUE THREAD

**Issue by uhkeller** [oniatsu/HotSwitch#12]
When I try to assign shortcuts to windows belonging to LibreOffice and RStudio, the shortcuts are often assigned to _other_ windows belonging to the same application. I haven't checked if this is limited to only these two applications. I'm on macOS 10.14.6.

Here is the HowSwitch window after I press space on an entry:
<img width="547" alt="1 after pressing space" src="https://user-images.githubusercontent.com/2323704/84295703-364af380-ab4b-11ea-91bc-f5b6f8d2ced9.png">

Then I press a but the shortcut is assigned to the window below:
<img width="551" alt="2 after pressing b" src="https://user-images.githubusercontent.com/2323704/84295711-3945e400-ab4b-11ea-83a6-4c921914674d.png">

Now I try again and press space and b, now the assignment works.
<img width="547" alt="3 after pressing space and b again" src="https://user-images.githubusercontent.com/2323704/84295715-3a771100-ab4b-11ea-9a54-cca86200dc86.png">

But it gets weirder. Now I want to delete the a shortcut. I press the down arrow…
<img width="544" alt="4 before pressing delete" src="https://user-images.githubusercontent.com/2323704/84295719-3a771100-ab4b-11ea-93d9-bd51f1841796.png">

And press delete. Now the shortcut of the window _above_ disappears, and the current window's shortcut switches to the one the window above used to have.
<img width="545" alt="5 after pressing delete" src="https://user-images.githubusercontent.com/2323704/84295721-3b0fa780-ab4b-11ea-8e3e-b2f55679c453.png">

**Comment by oniatsu** [comment]
Thank you for your report.
That is a known issue, but the fixing is a bit difficult. It causes on any apps.

I note the cause below.

---

Setting key is related with order by generated windows.

Scene 1
- Old window A on Chrome (registered key: none)
- New window B on Chrome (registered key: none)

Whether you set key with window A or B, the key is registered with OLD window A.

Scene 2
- Old window A on Chrome (registered key: X)
- New window B on Chrome (registered key: none)

When the key was already registered with old window, you can finally register a key with new window.

Scene 3
- Old window A on Chrome (registered key: X)
- New window B on Chrome (registered key: Y)

So, you cannot register a key only with new window without old one.

Invalid scene (impossible)
- Old window A on Chrome (registered key: none)
- New window B on Chrome (registered key: Y)

That is because the registered keys is saved by simple array structure.
The array key is related with window in order from the oldest.
So, when the scene 3, the key is saved by `[X, Y]` .
If the key Y is deleted, the key array would be `[X]` .

Scene 4
- Old window A on Chrome (registered key: Y) (X was changed to Y)
- New window B on Chrome (registered key: none)

To fix the issue, changing key saving structure is required.
That is why the solving it is a bit difficult.

**Comment by oniatsu** [comment]
I fixed this on [HotSwitch-HS](https://github.com/oniatsu/HotSwitch-HS).
HotSwitch-HS is a substitution of HotSwitch.

**Comment by uhkeller** [comment]
Just to confirm that it works much better now in HotSwitch-HS. Some minor issues persist that I will report over there. Thanks!
